/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp_subneting;

import java.awt.List;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leonard
 */
public class TP_subneting extends javax.swing.JFrame {

    private String ip_classe = "";
    
    private String[] tab_ip_bin={"","","",""};
    private String[] tab_masque_peso_bin={"","","",""};

    /**
     * Creates new form TP_subneting
     */
    public TP_subneting() {
        
        
       // System.out.print(convert_binaire_to_int("11110000"));
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_valide = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_octe_1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_octe_2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_octe_3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_octe_4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_octe_5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_nbr_sous_reseau = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel_resultat_masque_perso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_valide.setText("Valider");
        btn_valide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_valideActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Quel est votre Réseau ?");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TP  SUBNETING  ESM BENIN ");

        jTextField_octe_1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_octe_1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_octe_1FocusLost(evt);
            }
        });
        jTextField_octe_1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_octe_1InputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jTextField_octe_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_octe_1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel3.setText("IP : ");

        jTextField_octe_2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_octe_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_octe_2FocusLost(evt);
            }
        });
        jTextField_octe_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_octe_2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel4.setText(".");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel5.setText(".");

        jTextField_octe_3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_octe_3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_octe_3FocusLost(evt);
            }
        });
        jTextField_octe_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_octe_3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel6.setText(".");

        jTextField_octe_4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_octe_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_octe_4FocusLost(evt);
            }
        });
        jTextField_octe_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_octe_4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel7.setText("/");

        jTextField_octe_5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextField_octe_5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_octe_5FocusLost(evt);
            }
        });
        jTextField_octe_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_octe_5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel8.setText("Nbr sous réseau : ");

        jTextField_nbr_sous_reseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nbr_sous_reseauActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N", "Reseau ", "1er adresse Ip", "Dernier Adress Ip","Brodcast"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel_resultat_masque_perso.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel_resultat_masque_perso.setText(" ");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Réaliser par Bassarou YACOUBOU  © 2021");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_resultat_masque_perso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addGap(396, 396, 396))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_octe_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_octe_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_octe_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_octe_4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_octe_5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_nbr_sous_reseau, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_valide, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jTextField_octe_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jTextField_octe_4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jTextField_octe_3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jTextField_octe_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_octe_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nbr_sous_reseau, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btn_valide, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(55, 55, 55)
                .addComponent(jLabel_resultat_masque_perso)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_valideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_valideActionPerformed
      
          if(!jTextField_octe_1.getText().equals("") 
                && ! jTextField_octe_2.getText().equals("") 
                && !jTextField_octe_3.getText().equals("")
                && !jTextField_octe_4.getText().equals("")
                && !jTextField_octe_5.getText().equals("")
                 && !jTextField_nbr_sous_reseau.getText().equals("")
                
                )
        {
            
            int n=0;
            int s=Integer.parseInt(jTextField_nbr_sous_reseau.getText());
            
                //  JOptionPane.showMessageDialog(this, s);
            
            n=1;
            double a;
           // Math.pow(s, s)
            while(true)
              {
                  a=Math.pow(2, n);
                  
                  if(a< s+1){
                      n++;   
                  }
                  else{
                      
                      break;
                  }
                   
              }
            
            
          
            // JOptionPane.showMessageDialog(this, n);
             
             determine_masque_perso( n);
             
           
            
            
            
            
            
            
        }else{
            
             JOptionPane.showMessageDialog(this, "Attention verifier la saisie des informations");
        }
        
        
        
        
        
    }//GEN-LAST:event_btn_valideActionPerformed

    private void jTextField_octe_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_octe_1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_octe_1ActionPerformed

    private void jTextField_octe_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_octe_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_2ActionPerformed

    private void jTextField_octe_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_octe_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_3ActionPerformed

    private void jTextField_octe_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_octe_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_4ActionPerformed

    private void jTextField_octe_1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_octe_1InputMethodTextChanged

        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_octe_1InputMethodTextChanged

    private void jTextField_octe_1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_octe_1FocusLost
        // TODO add your handling code here:
        verifier_octe(jTextField_octe_1);
        determineClasse(jTextField_octe_1.getText());
      //  JOptionPane.showMessageDialog(this,  convert_int_to_binaire(Integer.parseInt(jTextField_octe_1.getText())) );
    }//GEN-LAST:event_jTextField_octe_1FocusLost

    private void jTextField_octe_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_octe_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_5ActionPerformed

    private void jTextField_nbr_sous_reseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nbr_sous_reseauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nbr_sous_reseauActionPerformed

    private void jTextField_octe_2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_octe_2FocusLost
        verifier_octe(jTextField_octe_2);        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_2FocusLost

    private void jTextField_octe_3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_octe_3FocusLost
        verifier_octe(jTextField_octe_3);
    }//GEN-LAST:event_jTextField_octe_3FocusLost

    private void jTextField_octe_4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_octe_4FocusLost

        verifier_octe(jTextField_octe_4);
    }//GEN-LAST:event_jTextField_octe_4FocusLost

    private void jTextField_octe_5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_octe_5FocusLost
        verifier_default_masque(jTextField_octe_5.getText());
         
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_octe_5FocusLost

    
    public void determine_masque_perso(int n) {
        
        int nbr_bit_un=0;
        
        String ip="";
        
          String[] entetes = { "N", "Reseau ", "1er adresse Ip", "Dernier Adress Ip","Brodcast"  } ;
          String donnees[][] = new String[100][5];
          
           DefaultTableModel model;
           
            
        
        switch (this.ip_classe) 
        {

            case "A":
                nbr_bit_un=n+8;
                
                for( int i=0 ; i<32 ; i++)
                {
                    if(nbr_bit_un <=0){
                     ip=ip+"0"    ;
                    }else{
                       ip=ip+"1"   ;  
                    }
                    
                  nbr_bit_un--;  
                    
                }
                
                
               
                break;

            case "B":

               nbr_bit_un=n+16;
               
                for( int i=0 ; i<32 ; i++)
                {
                    if(nbr_bit_un <=0){
                     ip=ip+"0"    ;
                    }else{
                       ip=ip+"1"   ;  
                    }
                    
                      nbr_bit_un--;   
                }
                break;

            case "C":

                nbr_bit_un=n+24;
                
                 for( int i=0 ; i<32 ; i++)
                {
                    if(nbr_bit_un <=0){
                     ip=ip+"0"    ;
                    }else{
                       ip=ip+"1"   ;  
                    }
                    
                     nbr_bit_un--;    
                }
                break;

        }
        
        
    
       
        
        System.out.println(ip);
       System.out.println(ip.substring(0,8));
        System.out.println(ip.substring(8,16));
         System.out.println(ip.substring(16,24));
           System.out.println(ip.substring(24,32));
        
         // System.out.println(this.tab_masque_peso_bin[0]);
         
         this.jLabel_resultat_masque_perso.setText("Le masque personalisé est : " 
                 + convert_binaire_to_int(ip.substring(0,8)) + '.'
                 + convert_binaire_to_int(ip.substring(8,16)) + '.'
                 + convert_binaire_to_int(ip.substring(16,24)) + '.'
                 + convert_binaire_to_int(ip.substring(24,32)) 
                 
                 
         );
         
         
         
         int plage_adress=0;
         int v=0;
           switch (this.ip_classe) {

            case "A":
                
                plage_adress=256 - convert_binaire_to_int(ip.substring(8,16));
                
                
                v=0;
                for(int i=0; i<Integer.parseInt(jTextField_nbr_sous_reseau.getText()) ;i++ )
                {
                    if(i==0){
                       v=0; 
                    }else{
                      v=v+  plage_adress;
                    }
                    System.out.println(jTextField_octe_1.getText()+"."+v+".0.0");
                    
                   donnees[i][0]=i+1+"";
                   donnees[i][1]=jTextField_octe_1.getText()+"."+v+".0.0";
                   donnees[i][2]=jTextField_octe_1.getText()+"."+ v +".0.1";
                   donnees[i][3]=jTextField_octe_1.getText()+"."+(v+(plage_adress-1))+".255.254";
                   donnees[i][4]=jTextField_octe_1.getText()+"."+(v+(plage_adress-1)) +".255.255";
                }
                
                   model = new DefaultTableModel(donnees, entetes);
      
                jTable1.setModel(model);
                
                
                break;

            case "B":

                plage_adress=256-convert_binaire_to_int(ip.substring(16,24));
                
                v=0;
                for(int i=0; i<Integer.parseInt(jTextField_nbr_sous_reseau.getText()) ;i++ )
                {
                    if(i==0){
                       v=0; 
                    }else{
                      v=v+  plage_adress;
                    }
                    System.out.println(jTextField_octe_1.getText()+"."+v+".0.0");
                    
                   donnees[i][0]=i+1+"";
                   donnees[i][1]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+v+".0";
                   donnees[i][2]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+ v +".1";
                   donnees[i][3]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+(v+(plage_adress-1))+".254";
                   donnees[i][4]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+(v+(plage_adress-1)) +".255";
                }
                
                  model = new DefaultTableModel(donnees, entetes);
      
                jTable1.setModel(model);
                
                break;

            case "C":
                 plage_adress=256-convert_binaire_to_int(ip.substring(24,32));
                 
                  v=0;
                for(int i=0; i<Integer.parseInt(jTextField_nbr_sous_reseau.getText()) ;i++ )
                {
                    if(i==0){
                       v=0; 
                    }else{
                      v=v+  plage_adress;
                    }
                    System.out.println(jTextField_octe_1.getText()+"."+v+".0.0");
                    
                   donnees[i][0]=i+1+"";
                   donnees[i][1]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+jTextField_octe_3.getText()+"."+v ;
                   donnees[i][2]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+jTextField_octe_3.getText()+"."+ (v+1);
                   donnees[i][3]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+jTextField_octe_3.getText()+"."+(v+(plage_adress-2));
                   donnees[i][4]=jTextField_octe_1.getText()+"."+jTextField_octe_2.getText()+"."+jTextField_octe_3.getText()+"."+(v+(plage_adress-1));
                }
                
                  model = new DefaultTableModel(donnees, entetes);
      
                jTable1.setModel(model);
                  break;
           }
           
           
           
           

         
         
       
      
        
        
       
          


         
    }
    
       
    public String convert_int_to_binaire ( int v)
    {
        
        int s1=v%2;
        int s2= (v/2)%2;
        int s3= ((v/2)/2)%2;
        int s4= (((v/2)/2)/2)%2;
        int s5= ((((v/2)/2)/2)/2)%2;
        int s6= (((((v/2)/2)/2)/2)/2)%2;
        int s7= ((((((v/2)/2)/2)/2)/2)/2)%2;
        int s8=(((((((v/2)/2)/2)/2)/2)/2)/2)%2;
        
     
        return ""+s1+""+s2+""+s3+""+s4+""+s5+""+s6+""+s7+""+s8+"";
        
    }
    
    public int convert_binaire_to_int ( String v){
        
        
        int j=128;
        int r=0;
        for(int i=0 ; i< v.length(); i++){
            
            if (v.charAt(i)=='1'){
                
               r=r+j; 
            } 
            j=j/2;
            
        }
        
        return r;
        
        
    }
    
    public void determineClasse(String value) {

        int v = Integer.parseInt(value);

        if (v >= 1 && v <= 127) {

            this.ip_classe = "A";

        } else {

            if (v >= 128 && v <= 191) {
                this.ip_classe = "B";

            } else {

                if (v >= 192 && v <= 223) {
                    this.ip_classe = "C";

                }
            }
        }

    }

    public void verifier_default_masque(String value) {

        int v=0 ;
        
          try {
                  v = Integer.parseInt(value);
            
        } catch (NumberFormatException e) {
          
            JOptionPane.showMessageDialog(this, "Attention  a vos saisies");
           

        }

         

        switch (this.ip_classe) {

            case "A":

                if (v != 8) {

                    JOptionPane.showMessageDialog(this, "Attention le masque par defaut n'est pas correct");
                }
                break;

            case "B":

                if (v != 16) {

                    JOptionPane.showMessageDialog(this, "Attention le masque par defaut n'est pas correct");
                }
                break;

            case "C":

                if (v != 24) {

                    JOptionPane.showMessageDialog(this, "Attention le masque par defaut n'est pas correct");
                }
                break;

        }

    }

    public void verifier_octe(JTextField field) {

        int value = 0;

        try {
            //  Block of code to try
            value = Integer.parseInt(field.getText());
        } catch (Exception e) {
            //  Block of code to handle errors
            JOptionPane.showMessageDialog(this, "Attention l'octe  entre 0 - 255 ");
            field.setText("");
            
            
             // field .setFocusable(false);
            //field.requestFocus();
//             field.setFocusable(true);
//             field.setFocusCycleRoot(true);

        }

        //  JOptionPane.showMessageDialog(this,value );
        if (!(value >= 0 && value <= 255)) {

            JOptionPane.showMessageDialog(this, "Attention l'octe n'est pas   entre 0 - 255 ");
            field.setText("");
             field.setFocusable(false);
//             field.setFocusable(true);
//             field.setFocusCycleRoot(true);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP_subneting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP_subneting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP_subneting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP_subneting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP_subneting().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_valide;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_resultat_masque_perso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_nbr_sous_reseau;
    private javax.swing.JTextField jTextField_octe_1;
    private javax.swing.JTextField jTextField_octe_2;
    private javax.swing.JTextField jTextField_octe_3;
    private javax.swing.JTextField jTextField_octe_4;
    private javax.swing.JTextField jTextField_octe_5;
    // End of variables declaration//GEN-END:variables
}
